name: Completion Spec Issue
title: "[CLI_NAME]"
description: All issues relating to specific CLI tools (e.g. `git`, `kubectl`, `chmod`)
body:
  - type: checkboxes
    attributes:
      label: Sanity checks
      options:
        - label: "My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec)."
          required: true
        - label: "I have searched [existing issues](https://github.com/tinecli/autocomplete/issues?q=) and there are no duplicates of my issue"
          required: true
  - type: input
    attributes:
      label: What CLI tool does this relate to?
      placeholder: "git"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which statement makes the most sense?
      options:
        - "There is a bug with this completion spec"
        - "There are errors with this completion spec"
        - "This completion spec does not exist"
        - "This completion spec isn't complete"
        - "Something else"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Details
      description: Tell us more about the issue
      placeholder: What subcommands / options / arguments are relevant? If a generator needs to be written, please specify the desired output.
    validations:
      required: true
